states: #Maps from name of state to FSMState.mode
  "STATE_0": 0 # FSMState.LANE_FOLLOWING=0 
  "STATE_1": 1 # FSMState.COORDINATION=1 
  "STATE_2": 2 # FSMState.INTERSECTION_CONTROL=2
events: #Maps from subscribing topic to singal ids
  "signal_0": "~topic_0"
  "signal_1": "~topic_1"
  "signal_2": "~topic_2"
# Define state transitions
transitions:
  STATE_0:
    "signal_0": "STATE_0"
    "signal_1": "STATE_1"
  STATE_1:
    "signal_0": "STATE_0"
    "signal_2": "STATE_2"
  STATE_2:
    "signal_1": "STATE_1"