states: #Maps from name of state to FSMState.mode
  "STATE_0": 0
  "STATE_1": 1
  "STATE_2": 2
events: #Maps from subscribing topic to singal ids
  "signal_0": 0
  "signal_1": 1
  "signal_2": 2
# Define state transitions
transitions:
  STATE_0:
    "signal_1": "STATE_1"
  STATE_1:
    "signal_0": "STATE_0"
    "signal_2": "STATE_2"
  STATE_2:
    "signal_1": "STATE_1"