mode_topic: "fsm_node/mode"
source_topics: #Mapping for name to topics
  lane: "lane_controller_node/wheels_control"
  intersection: "open_loop_intersection_control_node/wheels_cmd"
  coordination: "~coord_cmd"
mappings: #Mapping from FSMStates to names
  LANE_FOLLOWING: "lane"
  INTERSECTION_CONTROL: "intersection"
  COORDINATION_CONTROL: "coordination"