# Initail state of the FSM
initial_state: "JOYSTICK_CONTROL"


events: #Maps from subscribing topic to singal ids
  joystick_control_on: 
    topic: "parallel_autonomy_node/joystick_control"
    msg_type: "BoolStamped"
    trigger: True
  joystick_control_off: 
    topic: "parallel_autonomy_node/joystick_control"
    msg_type: "BoolStamped"
    trigger: False
  at_stop_line:
    topic: "stop_line_filter_node/at_stop_line"
    msg_type: "BoolStamped"
    trigger: True
  intersection_go:
    topic: "veh_coordinator_node/intersection_go"
    msg_type: "BoolStamped"
    trigger: True
  intersection_done:
    topic: "open_loop_intersection_control_node/intersection_done"
    msg_type: "BoolStamped"
    trigger: True



# Define nodes 
nodes:
  # anti_instagram_node: "anti_instagram_node/switch"
  apriltag_global_node: "apriltags_preprocessing_node/global_switch"
  apriltag_fast_node: "apriltags_preprocessing_node/fast_switch"
  vehicle_detector_node: "vehicle_detection_node/switch"
  # led_detector_node: "LED_detection_node/switch"
  static_object_detector_node: "static_object_detector_node/switch"
  line_detector_node: "line_detector_node/switch"
  lane_filter_node: "lane_filter_node/switch"
  stop_line_filter_node: "stop_line_filter_node/switch"

# Define state transitions
states:
  JOYSTICK_CONTROL:
    transitions:
      at_stop_line: "WAITING_ON_TURN_DIRECTION"
      out_of_lane: "LANE_FOLLOWING"
      joystick_control_off: "LANE_FOLLOWING"
      # TODO add obj and veh detection
      

    active_nodes: []
  LANE_FOLLOWING:
    transitions:
      at_stop_line: "WAITING_ON_TURN_DIRECTION"
      joystick_control_on: "JOYSTICK_CONTROL"
      # TODO add obj and veh detection

    active_nodes:
      - vehicle_detector_node
      - static_object_detector_node
      - lane_filter_node
      - line_detector_node
      - stop_line_filter_node
      - anti_instagram_node
    lights:
  WAITING_ON_TURN_DIRECTION:
    transitions:
      intersection_go: "INTERSECTION_CONTROL"
  INTERSECTION_CONTROL:
    transitions:
      intersection_done: "LANE_FOLLOWING"
    active_nodes: []
