initial_state: "STATE_0"
events: #Maps from subscribing topic to singal ids
  signal_0: "~topic_0"
  signal_1: "~topic_1"
  signal_2: "~topic_2"
# Define state transitions
transitions:
  STATE_0:
    signal_1: "STATE_1"
  STATE_1:
    signal_0: "STATE_0"
    signal_2: "STATE_2"
  STATE_2:
    signal_1: "STATE_1"
    signal_0: "STATE_3"
  STATE_3: {} #Terminal state