img_size: [240,320]
top_cutoff: 90
dilation_kernel_size: 3
canny_thresholds: [80,200]
hough_threshold: 20
hough_min_line_length: 3
hough_max_line_gap:    1


hsv_white1:  [0,0,200]
hsv_white2:  [255,100,255]
hsv_yellow1: [25,150,150]
hsv_yellow2: [45,255,255]
hsv_red1:    [0,100,120]
hsv_red2:    [10,255,255]
hsv_red3:    [245,100,120]
hsv_red4:    [255,255,255]
