# Parameters for open_loop_intersection_node
# #Turn right through intersection
turn_left: #distance, angle
  - [0.36, 0.0]
  - [0.0, 1.57]
  - [0.36,0.0]
turn_right:
  - [0.36, 0.0]
  - [0.0, -1.57]
  - [0.36, 0.0]
turn_forward:
  - [0.36, 0.0]
  - [0.0, 0.0]
  - [0.36, 0.0]
# turn_stop:
#   - [0.2, 0.0, 0.0]
