# Parameters for open_loop_intersection_node

#Turn right through intersection
#wheel vel and time
#first straight leg
tr_straight1_vel: 
tr_straight1_time:

#rotate right
tr_turn_vel: 
tr_turn_time:

#second straight leg
tr_straight2_vel: 
tr_straight2_time:

#Turn left through intersection
#wheel vel and time
#first straight leg
tl_straight1_vel: 
tl_straight1_time:

#rotate left
tl_turn_vel: 
tl_turn_time:

#second straight leg
tl_straight2_vel: 
tl_straight2_time:

#Go straight through intersection
#wheel vel and time
#straight leg
st_straight1_vel: 
st_straight1_time:
