# Parameters for open_loop_intersection_node
# #Turn right through intersection
turn_left: #distance, angle
  - [2.0, 0.5, 3.14]
  - [0.1, 0.0, 0.0]
  - [0.1, 0.5, 0.0]
turn_right:
  - [1.25, 0.5, -3.14]
  - [0.1, 0.0, 0.0]
  - [0.5, 0.35, 0.0]
turn_forward:
  - [2.0, 0.5, 0.0]
  - [0.1, 0.0, 0.0]
  - [2.0, 0.36, 0.0]
# turn_stop:
#   - [0.2, 0.0, 0.0]
