# Parameters for apriltags preprocessing
fast_enabled: 1
fast_period: 0.25
fast_v_crop: 180
fast_v_off:  -50
fast_h_crop: 150
fast_x_down:  2.0
global_enabled: 1
global_period: 2.0
global_v_off:   0
global_v_crop:  100
global_h_crop:  100
global_x_down:  1.4
