 # self.hsv_white1 = np.array([0, 0, 150])
 #        self.hsv_white2 = np.array([180, 50, 255]) 
 #        self.hsv_yellow1 = np.array([25, 120, 90])
 #        self.hsv_yellow2 = np.array([45, 255, 255]) 
 #        self.hsv_red1 = np.array([0, 140, 100])
 #        self.hsv_red2 = np.array([15, 255, 255]) 
 #        self.hsv_red3 = np.array([165, 140, 100])
 #        self.hsv_red4 = np.array([180, 255, 255]) 
 #        self.rgb_red = np.array([240, 20, 20])
 #        self.rgb_yellow = np.array([240, 240,60])
 #        self.rgb_white = np.array([240, 240, 240])
 #        self.rgb_road = np.array([60,60,60])