  # default parameters for forward_kinematics_node and inverse_kinematics_node
  K_l:          28.6
  K_r:          25.9
  radius_l:     0.02
  radius_r:     0.02
  baseline_lr:  0.217
  theta_dot_weights: [-2.0]
  v_weights: [2.0]
