  # default parameters for forward_kinematics_node and inverse_kinematics_node
  K_l:          28.6
  K_r:          25.9
  radius_l:     0.02
  radius_r:     0.02
  baseline_lr:  0.217
  learner_duty_threshold: 0.1
  fi_theta_dot_function: Duty_fi_theta_dot_naive
  fi_v_function: Duty_fi_v_naive
  theta_dot_weights: [-1.0]
  v_weights: [1.0]
#  theta_dot_weights: [0.5]
#  v_weights: [1.01867201]
#  fi_theta_dot_function: Duty_fi_linear
#  fi_v_function: Duty_fi_linear
#  theta_dot_weights: [0.0 -0.5 0.5]
#  v_weights: [0.0 0.5 0.5]
