  # default parameters for forward_kinematics_node and inverse_kinematics_node
  fi_theta_dot_function_param: Duty_fi_linear_no_constant
  fi_v_function_param: Duty_fi_linear_no_constant
  theta_dot_weights_param: [-3.049260309, 2.702093332]
  v_weights_param: [0.2673846771, 0.2396944977]
  learner_duty_threshold: 0.1
  learner_number_of_zero_entries: 10
  learner_number_of_v_samples: 150
  learner_number_of_theta_dot_samples_per_direction: 100