  # default parameters for forward_kinematics_node and inverse_kinematics_node
  K_l:          28.6
  K_r:          25.9
  radius_l:     0.02
  radius_r:     0.02
  baseline_lr:  0.217
  fi_theta_dot_function_param: Duty_fi_linear
  fi_v_function_param: Duty_fi_linear
  theta_dot_weights_param: [0.0, -2.6359447, 2.387096774]
  v_weights_param: [0.0, 0.286, 0.259]
  learner_duty_threshold: 0.1
